name: Hugo check broken links
description: Checks the hugo documentation website for broken links

runs:
  using: 'composite'
  steps:
    - uses: BoundfoxStudios/action-hugo-link-check@v2
      with:
        skip: github\.com\/boundfoxstudios\/fairy-tale-defender\/(tree|edit|new|issues\/new)
        hugo-startup-wait-time: 60
        hugo-root: docs
        hugo-content-dir: docs/content
        hugo-config: docs/config.yaml
