name: Contributors List
description: | 
  Writes the contributors.json file to be read by the Unity project.
inputs:
  github-token:
    required: true
    description: GitHub Token
  ref:
    required: true
    description: The branch name to fetch
    default: develop
outputs:
  content:
    description: The JSON string containing build information.
    value: ${{ steps.content.outputs.value }}
  
runs:
  using: 'composite'
  steps:
    - name: Get Contributors from .all-contributorsrc
      id: content
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "value=$(gh api -H 'Accept: application/vnd.github.VERSION.raw' '/repos/BoundfoxStudios/fairy-tale-defender/contents/.all-contributorsrc?ref=${{ inputs.ref }}' | jq --compact-output '{ items: [.contributors[] | { user: .name, githubAccount: .login, contributions: .contributions }] }' )" >> $GITHUB_OUTPUT
      shell: sh
