name: Build Manifest
description: Generates a JSON string containing build information.
outputs:
  content:
    description: The JSON string containing build information.
    value: ${{ steps.content.outputs.value }}
  
runs:
  using: 'composite'
  steps:
    - name: Grab short SHA
      id: variables
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: sh
    - name: Set ouput
      id: content
      shell: sh
      run: | 
        echo "value={ \"sha\": \"${{ github.sha }}\", \"shortSha\": \"${{ steps.variables.outputs.sha_short }}\", \"runId\": ${{ github.run_id }}, \"runNumber\": ${{ github.run_number }} }" >> $GITHUB_OUTPUT 
        