# Reusable workflow for building the community project

name: Unity Build & Test Reusable Workflow

on: 
  workflow_call:
    inputs:
      project-path:
        required: false
        description: Path that points to the Unity project
        default: CommunityProject
        type: string
      custom-parameters:
        required: false
        default: ''
        description: Additional parameters to pass to Unity for building
        type: string
      do-test:
        required: false
        description: Whether to execute tests or not, defaults to false
        default: false
        type: boolean
      fail-fast:
        required: false
        description: Whether to fail fast in the matrix build strategy, defaults to false
        default: false
        type: boolean
      max-parallel:
        required: false
        description: Maximum amount of parallel matrix build strategy runners, defaults to 10
        default: 10
        type: number
    secrets:
      UNITY_EMAIL: 
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_SERIAL: 
        required: false
        description: Set the serial to use a professional license for building
      UNITY_LICENSE:
        required: false
        description: Set the license to use a personal license for building
  
jobs: 
  test:
    name: Test for ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    if: ${{ inputs.do-test }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/unity-cache
        with:
          project-path: ${{ inputs.project-path }}
          unity-version: ${{ matrix.unity-version }}
          target-platform: ${{ matrix.target-platform }}
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} 
        with:
          projectPath: ${{ inputs.project-path }}
          unityVersion: ${{ matrix.unity-version }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        unity-version:
          - 2021.3.9f1
        os:
          - ubuntu-latest
          # Game CI does not support MacOS yet for executing the tests
          # Regarding Windows see: https://github.com/BoundfoxStudios/community-project/issues/20
        include:
          - os: ubuntu-latest
            target-platform: StandaloneLinux64

  manifest:
    name: Generate build manifest json
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.manifest.outputs.content }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build-manifest
        id: manifest
      
  contributors:
    name: Generate contributors json
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.contributors.outputs.content }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/contributors
        id: contributors
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
  build:
    name: Build for ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    needs: [manifest, contributors]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/unity-cache
        with:
          project-path: ${{ inputs.project-path }}
          unity-version: ${{ matrix.unity-version }}
          target-platform: ${{ matrix.target-platform }}
      - name: write manifest.json
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
        uses: DamianReeves/write-file-action@master
        with:
         path: ${{ inputs.project-path }}/Assets/_Game/Build/manifest.json
         write-mode: overwrite
         contents: ${{ needs.manifest.outputs.content }}
      - name: write contributors.json
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
        uses: DamianReeves/write-file-action@master
        with:
         path: ${{ inputs.project-path }}/Assets/_Game/Build/contributors.json
         write-mode: overwrite
         contents: ${{ needs.contributors.outputs.content }}
      - name: Commit manifest & contributors changes
        if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v9
        with:
          push: false
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ inputs.project-path }}
          unityVersion: ${{ matrix.unity-version }}
          targetPlatform: ${{ matrix.target-platform }}
          versioning: Semantic
          buildName: CommunityProject
          customParameters: ${{ inputs.custom-parameters }}
      
      # We need to create a TAR archive before uploading due to possible permission loss
      # See: 
      #   - https://github.com/actions/upload-artifact#permission-loss
      #   - https://github.com/game-ci/unity-actions/issues/152
      - name: Create TAR archive
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          tar -czf Build-${{ github.run_id }}-${{ matrix.target-platform }}.tar ${{ matrix.target-platform }}
          mv  Build-${{ github.run_id }}-${{ matrix.target-platform }}.tar ${{ matrix.target-platform }}
          find . -not -name '*.tar' -delete
        shell: bash
        working-directory: build
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ github.run_id }}-${{ matrix.target-platform }}
          path: build/${{ matrix.target-platform }}
          if-no-files-found: error
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        unity-version:
          - 2021.3.9f1
        os:
          - windows-2019
          - macos-latest
          - ubuntu-latest
        include:
          - os: windows-2019
            target-platform: StandaloneWindows64
          - os: macos-latest
            target-platform: StandaloneOSX
          - os: ubuntu-latest
            target-platform: StandaloneLinux64
    