name: Development

on: 
  push:
    branches:
      - develop
    paths:
      - 'FairyTaleDefender/Assets/**'
      - 'FairyTaleDefender/Packages/**'
      - 'FairyTaleDefender/ProjectSettings/**'
  workflow_dispatch:

jobs: 
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linter

  build:
    needs: lint
    name: Development Builds
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_PERSONAL_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_PERSONAL_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PERSONAL_PASSWORD }}
    with:
      do-test: true
      do-upload-game-binaries: true
      do-upload-debug-symbols: true
      fail-fast: true
      ref: ${{ github.ref }}
      custom-parameters: -Development -AllowDebugging

  notarize:
    needs: build
    name: Notarize the macOS build
    uses: ./.github/workflows/notarization.yml
    secrets:
      APPLE_CERTIFICATE_DATA: ${{ secrets.APPLE_CERTIFICATE_DATA }}
      APPLE_CERTIFICATE_PASSPHRASE: ${{ secrets.APPLE_CERTIFICATE_PASSPHRASE }}
      APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
      APPLE_NOTARIZATION_USERNAME: ${{ secrets.APPLE_NOTARIZATION_USERNAME }}
      APPLE_NOTARIZATION_PASSWORD: ${{ secrets.APPLE_NOTARIZATION_PASSWORD }}
  
  deploy-to-steam:
    needs: [build, notarize]
    name: Upload the game to the CI steam branch
    uses: ./.github/workflows/steam.yml
    with:
      app-id: 2350330
      branch: develop
      build-description: ${{ needs.build.outputs.build-version }}-${{ github.run_id }}
    secrets:
      USERNAME: ${{ secrets.STEAM_BUILDER_USERNAME }}
      PASSWORD: ${{ secrets.STEAM_BUILDER_PASSWORD }}
      CONFIG_VDF: ${{ secrets.STEAM_BUILDER_CONFIG_VDF }}
      SSFN_FILE_NAME: ${{ secrets.STEAM_BUILDER_SSFN_FILE_NAME }}
      SSFN_FILE_CONTENTS: ${{ secrets.STEAM_BUILDER_SSFN_FILE_CONTENTS }}