name: Documentation Website

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '.all-contributorsrc'
      - 'resources/Blendfiles/Props.blend'
      - 'resources/Blendfiles/Starter.blend'
      - 'resources/Blendfiles/Tiles.blend'
      - 'resources/ColorPalettes/**'
      - 'resources/Windscale/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        default: ''
        required: true
        description: The ref to checkout.
        type: string
  schedule:
    - cron: '5 17 * * 1' # deploy the documentation website every monday after the new video went live

env:
  HUGO_YOUTUBE_API_KEY: ${{ secrets.HUGO_YOUTUBE_API_KEY }}

jobs:
  convert-color-palette-summer:
    uses: ./.github/workflows/psd-to-png.yml
    with:
       ref: ${{ inputs.ref }}
       input-file: ./resources/ColorPalettes/ColorPalette_Summer.psd
       output-filename: ColorPalette_Summer.png

  convert-windscale:
    uses: ./.github/workflows/psd-to-png.yml
    with:
       ref: ${{ inputs.ref }}
       input-file: ./resources/Windscale/Windscale.psd
       output-filename: Windscale.png

  convert-color-palette-summer-description:
    uses: ./.github/workflows/psd-to-png.yml
    with:
       ref: ${{ inputs.ref }}
       input-file: ./resources/ColorPalettes/ColorPalette_Summer_Description.psd
       output-filename: ColorPalette_Summer_Description.png

  create-blender-starter-kit:
    runs-on: ubuntu-latest
    needs: [convert-color-palette-summer, convert-windscale]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - run: mkdir BlenderStarterKit
      - run: cp ./resources/Blendfiles/Props.blend ./BlenderStarterKit
      - run: cp ./resources/Blendfiles/Tiles.blend ./BlenderStarterKit
      - run: cp ./resources/Blendfiles/Starter.blend ./BlenderStarterKit
      - uses: actions/download-artifact@v3
        with:
          name: ColorPalette_Summer.png
          path: ./BlenderStarterKit/textures/
      - uses: actions/download-artifact@v3
        with:
          name: Windscale.png
          path: ./BlenderStarterKit/textures
      - run: zip ./BlenderStarterKit/BlenderStarterKit.zip ./BlenderStarterKit/**/*.*
      - uses: actions/upload-artifact@v3
        with:
          name: BlenderStarterKit
          path: ./BlenderStarterKit/BlenderStarterKit.zip
  
  check-broken-links:
    runs-on: ubuntu-latest
    needs: [create-blender-starter-kit, convert-color-palette-summer-description]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/actions/download-all-psd-to-png-artifacts
      - uses: ./.github/actions/hugo-check-broken-links

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_call'
    needs: [check-broken-links, create-blender-starter-kit, convert-color-palette-summer-description]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/download-all-psd-to-png-artifacts
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: docs
      - run: npm run publish
        working-directory: docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          user_name: "Boundfox Studios Publish Bot"
          user_email: "info@boundfoxstudios.com"
          commit_message: ":rocket: Deploy Docs"
          cname: docs.fairytaledefender.de
