name: Documentation Website

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '.all-contributorsrc'
      - 'resources/BlenderStarterKit/**'
      - 'resources/ColorPalette/**'
  workflow_dispatch:
  schedule:
    - cron: '5 17 * * 1' # deploy the documentation website every monday after the new video went live

env:
  HUGO_YOUTUBE_API_KEY: ${{ secrets.HUGO_YOUTUBE_API_KEY }}

jobs:
  create-blender-starter-kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir .blender-tmp
      - run: cp ./resources/BlenderStarterKit/*.blend ./.blender-tmp
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install @webtoon/psd@0.3.0 pngjs@6.0.0
      - uses: actions/github-script@v6
        with:
          script: |
            import Psd from "@webtoon/psd";
            import pngjs from 'pngjs';
            import * as fs from 'fs';

            const PNG = pngjs.PNG;

            const psdData = fs.readFileSync('./resources/ColorPalette/ColorPalette_Summer.psd');
            const psdFile = Psd.parse(psdData.buffer);

            const pixelData = await psdFile.composite();

            const png = new PNG({ width: psdFile.width, height: psdFile.height });
            png.data = Buffer.from(pixelData);
            png.pack().pipe(fs.createWriteStream('./.blender-tmp/ColorPalette_Summer.png'));
      - run: rm ./.blender-tmp/*.psd
      - run: zip ./.blender-tmp/BlenderStarterKit.zip ./.blender-tmp/*.*
      - uses: actions/upload-artifact@v3
        with:
          name: BlenderStarterKit
          path: ./.blender-tmp/BlenderStarterKit.zip
  
  check-broken-links:
    runs-on: ubuntu-latest
    needs: [create-blender-starter-kit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: BlenderStarterKit
          path: docs/static
      - uses: ./.github/actions/hugo-check-broken-links

  deploy:
    runs-on: ubuntu-latest
    needs: [check-broken-links, create-blender-starter-kit]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: BlenderStarterKit
          path: docs/static
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: docs
      - run: npm run publish
        working-directory: docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          user_name: "Boundfox Studios Publish Bot"
          user_email: "info@boundfoxstudios.com"
          commit_message: ":rocket: Deploy Docs"
