name: PSD to PNG

on:
  workflow_call:
    inputs:
      input-file:
        type: string
        required: true
        description: Path to the input PSD file.
      output-filename:
        type: string
        required: true
        description: The name of the output file.
      ref: 
        type: string
        required: true
        description: The ref to checkout.

jobs:
  psd-to-png:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install @webtoon/psd@0.3.0 pngjs@6.0.0
      - uses: actions/github-script@v6
        with:
          script: |
            const { default: Psd } = await import('${{ github.workspace }}/node_modules/@webtoon/psd/dist/index.js');
            const PNG = require('pngjs').PNG;
            const fs = require('fs');

            const psdData = fs.readFileSync('${{ inputs.input-file }}');
            const psdFile = Psd.parse(psdData.buffer);

            const pixelData = await psdFile.composite();

            const png = new PNG({ width: psdFile.width, height: psdFile.height });
            png.data = Buffer.from(pixelData);
            png.pack().pipe(fs.createWriteStream('./${{ inputs.output-filename }}'));
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.output-filename }}
          path: ./${{ inputs.output-filename }}
