# Reusable workflow to upload to a steam branch

name: Steam

on:
  workflow_call:
    inputs:
      branch:
        required: true
        description: The Steam branch to deploy to
        type: string
      build-description:
        required: true
        description: Build description, e.g. the semantic version
        type: string
      app-id:
        required: true
        description: The app's steam app id
        type: number
    secrets:
      USERNAME:
        required: true
      PASSWORD:
        required: true
      CONFIG_VDF:
        required: true
      SSFN_FILE_NAME:
        required: true
      SSFN_FILE_CONTENTS:
        required: true

jobs:
  deploy-to-steam:
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-${{ github.run_id }}-StandaloneWindows64
          path: build/StandaloneWindows64
      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-${{ github.run_id }}-StandaloneOSX
          path: build/StandaloneOSX
      - name: Untar macOS artifact
        run: |
          cd build/StandaloneOSX
          tar -xf Build-${{ github.run_id }}-StandaloneOSX.tar --strip-components=1
          rm Build-${{ github.run_id }}-StandaloneOSX.tar
        shell: bash
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-${{ github.run_id }}-StandaloneLinux64
          path: build/StandaloneLinux64
      - uses: game-ci/steam-deploy@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          configVdf: ${{ secrets.CONFIG_VDF }}
          ssfnFileName: ${{ secrets.SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.SSFN_FILE_CONTENTS }}
          appId: ${{ inputs.app-id }}
          buildDescription: ${{ inputs.build-description }}
          rootPath: build
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneOSX
          depot3Path: StandaloneLinux64
          releaseBranch: ${{ inputs.branch }}